version: '3.1'

services:
  db:
    image: postgres:14.5
    container_name: postgres_academic
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data

